version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
      - redis
    environment:
      - DNS=host=db user=postgres password=123456 dbname=go_ecommerce port=5432 sslmode=disable
      - JWT_SECRET= inidiasecretnya
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: go_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
